[package]
name = "i2c_devices"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.29", default-features = false }
numtoa = "0.3.1"

[dev-dependencies]
log = "0.4.29"
rand = "0.9.2"

# features

[features]
default = ["std"]

std = []
