---
#
# If the committer has run the pre-commit hooks on their local machine and
# fixed all identified issues then this check is expected to run perfectly
# fine.
#

name: verify pull request

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  lint:
    name: lint the code
    runs-on: ubuntu-latest
    steps:
      # -------------------------------------------------------------------
      # prepare
      # -------------------------------------------------------------------
      - name: checkout repository
        uses: actions/checkout@v4
      - name: install uv
        uses: astral-sh/setup-uv@v5
      - name: identify changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          # release-please creates double-newlines which would be flagged
          # by markdownlint; the easiest fix is to ignore the file entirely
          files_ignore: |
            CHANGELOG.md
      # https://github.com/actions-rust-lang/setup-rust-toolchain
      - name: install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      # the reference 'origin/HEAD' may be missing on GHA runner
      # (will fail if you're not merging to the default branch)
      - name: ensure 'origin/HEAD' exists
        id: git-origin-head
        run: |
          git remote set-head origin --auto
      # -------------------------------------------------------------------
      # validate
      # -------------------------------------------------------------------
      # The GitHub Action 'pre-commit/action' uses '--all-files' and always
      # check against all files in the repository, even if the pull request
      # does not touch them. We don't want that. Review modified files only.
      - name: re-run pre-commit hooks
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          UV_NO_PROGRESS: true
        run: |
          uv tool install pre-commit
          pre-commit run --show-diff-on-failure --color=always --hook-stage pre-push --files $CHANGED_FILES
      - name: run unit tests (with code coverage report)
        run: |
          echo -e 'code coverage report:\n' > output.md
          echo '```TEXT' >> output.md
          cargo install cargo-llvm-cov
          set -o pipefail
          cargo llvm-cov --fail-under-lines=30 | tee -a output.md
          echo '```' >> output.md
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: output.md
